export interface NeighborhoodRaw {
  id: string;
  name: string;
  city: string;
  demandIndex: number;
  publicScarcityIndex: number;
  residentialSupplyIndex: number;
  citationDensity: number;
  poiProximityScore: number;
  commuterDensity: number;
  residentialParcelDensity: number;
  commercialParkingCount: number;
  zoningType: "residential" | "mixed" | "commercial";
  neighborhoodType: "urban-core" | "inner-suburb" | "outer-suburb" | "rural";
  centroid: [number, number];
  polygon: [number, number][];
}

function makeBox(
  latMin: number,
  latMax: number,
  lngMin: number,
  lngMax: number,
  steps = 0
): [number, number][] {
  if (steps === 0) {
    return [
      [lngMin, latMin],
      [lngMax, latMin],
      [lngMax, latMax],
      [lngMin, latMax],
      [lngMin, latMin],
    ];
  }
  const coords: [number, number][] = [];
  const latStep = (latMax - latMin) / steps;
  const lngStep = (lngMax - lngMin) / steps;
  for (let i = 0; i <= steps; i++) coords.push([lngMin + lngStep * i, latMin]);
  for (let i = 0; i <= steps; i++) coords.push([lngMax, latMin + latStep * i]);
  for (let i = steps; i >= 0; i--) coords.push([lngMin + lngStep * i, latMax]);
  for (let i = steps; i >= 0; i--) coords.push([lngMin, latMin + latStep * i]);
  coords.push([lngMin, latMin]);
  return coords;
}

export const SEATTLE_NEIGHBORHOODS: NeighborhoodRaw[] = [
  {
    id: "south-lake-union",
    name: "South Lake Union",
    city: "seattle",
    demandIndex: 92,
    publicScarcityIndex: 38,
    residentialSupplyIndex: 12,
    citationDensity: 4820,
    poiProximityScore: 91,
    commuterDensity: 18400,
    residentialParcelDensity: 28,
    commercialParkingCount: 18,
    zoningType: "commercial",
    neighborhoodType: "urban-core",
    centroid: [47.622, -122.338],
    polygon: makeBox(47.613, 47.631, -122.347, -122.328),
  },
  {
    id: "pioneer-square",
    name: "Pioneer Square",
    city: "seattle",
    demandIndex: 96,
    publicScarcityIndex: 18,
    residentialSupplyIndex: 5,
    citationDensity: 6100,
    poiProximityScore: 98,
    commuterDensity: 22000,
    residentialParcelDensity: 12,
    commercialParkingCount: 24,
    zoningType: "commercial",
    neighborhoodType: "urban-core",
    centroid: [47.6, -122.332],
    polygon: makeBox(47.595, 47.608, -122.337, -122.325),
  },
  {
    id: "capitol-hill",
    name: "Capitol Hill",
    city: "seattle",
    demandIndex: 75,
    publicScarcityIndex: 74,
    residentialSupplyIndex: 60,
    citationDensity: 3100,
    poiProximityScore: 76,
    commuterDensity: 9200,
    residentialParcelDensity: 210,
    commercialParkingCount: 7,
    zoningType: "mixed",
    neighborhoodType: "inner-suburb",
    centroid: [47.619, -122.314],
    polygon: makeBox(47.612, 47.627, -122.328, -122.298),
  },
  {
    id: "madrona-leschi",
    name: "Madrona / Leschi",
    city: "seattle",
    demandIndex: 68,
    publicScarcityIndex: 88,
    residentialSupplyIndex: 78,
    citationDensity: 1850,
    poiProximityScore: 65,
    commuterDensity: 4800,
    residentialParcelDensity: 420,
    commercialParkingCount: 2,
    zoningType: "mixed",
    neighborhoodType: "inner-suburb",
    centroid: [47.61, -122.282],
    polygon: makeBox(47.602, 47.62, -122.298, -122.265),
  },
  {
    id: "columbia-city",
    name: "Columbia City",
    city: "seattle",
    demandIndex: 60,
    publicScarcityIndex: 90,
    residentialSupplyIndex: 75,
    citationDensity: 1400,
    poiProximityScore: 57,
    commuterDensity: 3900,
    residentialParcelDensity: 380,
    commercialParkingCount: 2,
    zoningType: "mixed",
    neighborhoodType: "inner-suburb",
    centroid: [47.565, -122.283],
    polygon: makeBox(47.555, 47.578, -122.298, -122.265),
  },
  {
    id: "wallingford",
    name: "Wallingford",
    city: "seattle",
    demandIndex: 65,
    publicScarcityIndex: 85,
    residentialSupplyIndex: 80,
    citationDensity: 1620,
    poiProximityScore: 62,
    commuterDensity: 5200,
    residentialParcelDensity: 445,
    commercialParkingCount: 2,
    zoningType: "mixed",
    neighborhoodType: "inner-suburb",
    centroid: [47.661, -122.334],
    polygon: makeBox(47.655, 47.669, -122.348, -122.317),
  },
  {
    id: "west-seattle-junction",
    name: "West Seattle Junction",
    city: "seattle",
    demandIndex: 58,
    publicScarcityIndex: 86,
    residentialSupplyIndex: 82,
    citationDensity: 1380,
    poiProximityScore: 56,
    commuterDensity: 4200,
    residentialParcelDensity: 460,
    commercialParkingCount: 2,
    zoningType: "mixed",
    neighborhoodType: "inner-suburb",
    centroid: [47.563, -122.376],
    polygon: makeBox(47.555, 47.574, -122.39, -122.362),
  },
  {
    id: "fremont",
    name: "Fremont",
    city: "seattle",
    demandIndex: 72,
    publicScarcityIndex: 70,
    residentialSupplyIndex: 52,
    citationDensity: 2400,
    poiProximityScore: 70,
    commuterDensity: 7800,
    residentialParcelDensity: 240,
    commercialParkingCount: 5,
    zoningType: "mixed",
    neighborhoodType: "inner-suburb",
    centroid: [47.651, -122.351],
    polygon: makeBox(47.645, 47.66, -122.365, -122.337),
  },
  {
    id: "ballard",
    name: "Ballard",
    city: "seattle",
    demandIndex: 68,
    publicScarcityIndex: 72,
    residentialSupplyIndex: 58,
    citationDensity: 2100,
    poiProximityScore: 66,
    commuterDensity: 6800,
    residentialParcelDensity: 280,
    commercialParkingCount: 4,
    zoningType: "mixed",
    neighborhoodType: "inner-suburb",
    centroid: [47.665, -122.382],
    polygon: makeBox(47.655, 47.678, -122.398, -122.363),
  },
  {
    id: "u-district",
    name: "University District",
    city: "seattle",
    demandIndex: 78,
    publicScarcityIndex: 64,
    residentialSupplyIndex: 45,
    citationDensity: 2900,
    poiProximityScore: 79,
    commuterDensity: 11200,
    residentialParcelDensity: 180,
    commercialParkingCount: 9,
    zoningType: "mixed",
    neighborhoodType: "inner-suburb",
    centroid: [47.66, -122.313],
    polygon: makeBox(47.651, 47.669, -122.325, -122.295),
  },
  {
    id: "greenwood",
    name: "Greenwood",
    city: "seattle",
    demandIndex: 35,
    publicScarcityIndex: 90,
    residentialSupplyIndex: 82,
    citationDensity: 680,
    poiProximityScore: 33,
    commuterDensity: 2200,
    residentialParcelDensity: 510,
    commercialParkingCount: 1,
    zoningType: "residential",
    neighborhoodType: "inner-suburb",
    centroid: [47.686, -122.356],
    polygon: makeBox(47.677, 47.698, -122.368, -122.342),
  },
  {
    id: "phinney-ridge",
    name: "Phinney Ridge",
    city: "seattle",
    demandIndex: 30,
    publicScarcityIndex: 92,
    residentialSupplyIndex: 85,
    citationDensity: 520,
    poiProximityScore: 28,
    commuterDensity: 1900,
    residentialParcelDensity: 530,
    commercialParkingCount: 1,
    zoningType: "residential",
    neighborhoodType: "inner-suburb",
    centroid: [47.674, -122.352],
    polygon: makeBox(47.666, 47.684, -122.361, -122.34),
  },
  {
    id: "magnolia",
    name: "Magnolia",
    city: "seattle",
    demandIndex: 22,
    publicScarcityIndex: 93,
    residentialSupplyIndex: 90,
    citationDensity: 380,
    poiProximityScore: 20,
    commuterDensity: 1400,
    residentialParcelDensity: 580,
    commercialParkingCount: 1,
    zoningType: "residential",
    neighborhoodType: "outer-suburb",
    centroid: [47.646, -122.4],
    polygon: makeBox(47.634, 47.66, -122.418, -122.382),
  },
  {
    id: "georgetown",
    name: "Georgetown",
    city: "seattle",
    demandIndex: 48,
    publicScarcityIndex: 70,
    residentialSupplyIndex: 42,
    citationDensity: 1050,
    poiProximityScore: 46,
    commuterDensity: 3800,
    residentialParcelDensity: 160,
    commercialParkingCount: 5,
    zoningType: "mixed",
    neighborhoodType: "inner-suburb",
    centroid: [47.545, -122.316],
    polygon: makeBox(47.535, 47.558, -122.33, -122.302),
  },
  {
    id: "international-district",
    name: "International District",
    city: "seattle",
    demandIndex: 85,
    publicScarcityIndex: 35,
    residentialSupplyIndex: 18,
    citationDensity: 3800,
    poiProximityScore: 88,
    commuterDensity: 14200,
    residentialParcelDensity: 55,
    commercialParkingCount: 14,
    zoningType: "commercial",
    neighborhoodType: "urban-core",
    centroid: [47.598, -122.323],
    polygon: makeBox(47.593, 47.607, -122.33, -122.314),
  },
  {
    id: "bellevue-downtown",
    name: "Bellevue Downtown",
    city: "seattle",
    demandIndex: 88,
    publicScarcityIndex: 14,
    residentialSupplyIndex: 10,
    citationDensity: 4200,
    poiProximityScore: 86,
    commuterDensity: 17500,
    residentialParcelDensity: 25,
    commercialParkingCount: 22,
    zoningType: "commercial",
    neighborhoodType: "urban-core",
    centroid: [47.613, -122.201],
    polygon: makeBox(47.604, 47.624, -122.215, -122.184),
  },
  {
    id: "kirkland",
    name: "Kirkland Waterfront",
    city: "seattle",
    demandIndex: 55,
    publicScarcityIndex: 80,
    residentialSupplyIndex: 80,
    citationDensity: 1280,
    poiProximityScore: 53,
    commuterDensity: 4100,
    residentialParcelDensity: 395,
    commercialParkingCount: 4,
    zoningType: "mixed",
    neighborhoodType: "inner-suburb",
    centroid: [47.676, -122.204],
    polygon: makeBox(47.666, 47.685, -122.218, -122.186),
  },
  {
    id: "medina",
    name: "Medina / Clyde Hill",
    city: "seattle",
    demandIndex: 8,
    publicScarcityIndex: 98,
    residentialSupplyIndex: 95,
    citationDensity: 95,
    poiProximityScore: 7,
    commuterDensity: 420,
    residentialParcelDensity: 610,
    commercialParkingCount: 0,
    zoningType: "residential",
    neighborhoodType: "rural",
    centroid: [47.625, -122.225],
    polygon: makeBox(47.614, 47.638, -122.242, -122.208),
  },
  {
    id: "redmond",
    name: "Redmond",
    city: "seattle",
    demandIndex: 60,
    publicScarcityIndex: 54,
    residentialSupplyIndex: 40,
    citationDensity: 1380,
    poiProximityScore: 58,
    commuterDensity: 6800,
    residentialParcelDensity: 190,
    commercialParkingCount: 10,
    zoningType: "mixed",
    neighborhoodType: "outer-suburb",
    centroid: [47.673, -122.122],
    polygon: makeBox(47.663, 47.685, -122.14, -122.103),
  },
  {
    id: "bothell-kenmore",
    name: "Bothell / Kenmore",
    city: "seattle",
    demandIndex: 10,
    publicScarcityIndex: 94,
    residentialSupplyIndex: 92,
    citationDensity: 130,
    poiProximityScore: 9,
    commuterDensity: 560,
    residentialParcelDensity: 590,
    commercialParkingCount: 0,
    zoningType: "residential",
    neighborhoodType: "rural",
    centroid: [47.763, -122.207],
    polygon: makeBox(47.75, 47.783, -122.228, -122.186),
  },
];
